name: Build macOS App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.13.0'  # Use the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install py2app

      - name: Convert .svg to .icns
        run: |
          iconutil -c icns icon.iconset

      - name: Build with PyInstaller
        run: |
          python setup.py py2app
          codesign --force --deep --sign - dist/PDF_Resize.app

      #- name: Archive build
        #run: |
        #  mkdir -p dist-macos
        #  mv dist/PDF_Resize dist-macos/
        #  tar -czvf dist-macos.tar.gz dist-macos
      - name: Package .app into a .zip file
        run: |
          cd dist
          zip -r ../PDF_Resize.app.zip PDF_Resize.app

      - name: Upload artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: macOS-build
          path: PDF_Resize.app.zip
