name: Build macOS App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.13.0'  # Use the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          pip install pillow

      - name: Build with PyInstaller
        run: pyinstaller --onedir --windowed --icon=file-pdf-regular.svg PDF_Resize.py

      - name: Archive build
        run: |
          mkdir -p dist-macos
          mv dist/PDF_Resize dist-macos/
          tar -czvf dist-macos.tar.gz dist-macos

      - name: Upload artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: macOS-build
          path: dist-macos.tar.gz
